"""
orchestrator/onepager_evaluator.py
====================================
Executes the One-Pager evaluation (agent A10) after A8 generates the output.

Architecture:
    run_onepager_evaluation(diagnostico_id, onepager_output, runner)
        1. Load acceptance criteria from config/acceptance_criteria.json
        2. Invoke A10 via SessionRunner (system prompt is on the Agent object)
        3. Extract verdict from returned dict (aprobado, feedback, criterios_fallidos)
        4. Save evaluation to blackboard/onepager/{id}_eval.json
        5. Update diagnostico-state.json (onepager.eval_passed, eval_path, status)
        6. Return (passed, feedback) tuple

    On second failure: raises OnePagerEscalationError (human review required)

Raises:
    OnePagerEscalationError: One-Pager failed quality check twice.
    LLMError:                Unrecoverable API failure (raised by SessionRunner).
    AgentOutputError:        A10 returned unparseable output (raised by SessionRunner).
"""

from __future__ import annotations

import asyncio
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from orchestrator.exceptions import OrchestratorError
from orchestrator.session_runner import SessionRunner
from orchestrator import state_manager

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────────────

_ROOT = Path(__file__).parent.parent
_CONFIG_DIR = _ROOT / "config"
_ONEPAGER_DIR = _ROOT / "blackboard" / "onepager"


# ─────────────────────────────────────────────────────────────────────────────
# Custom exception
# ─────────────────────────────────────────────────────────────────────────────

class OnePagerEscalationError(OrchestratorError):
    """
    Raised when the One-Pager fails the quality check twice.
    Requires consultant review before it can be delivered to the client.
    """
    def __init__(self, diagnostico_id: str, last_feedback: str):
        self.diagnostico_id = diagnostico_id
        self.last_feedback = last_feedback
        super().__init__(
            f"One-Pager escalation: run '{diagnostico_id}' failed A10 evaluation twice. "
            f"Consultant review required.\n"
            f"Last feedback: {last_feedback}"
        )


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _load_acceptance_criteria() -> list[dict]:
    """Load the 8-item acceptance checklist from config/acceptance_criteria.json."""
    path = _CONFIG_DIR / "acceptance_criteria.json"
    if not path.exists():
        logger.warning("acceptance_criteria.json not found — A10 will evaluate without criteria")
        return []
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    return data.get("criterios", [])


def _save_onepager_evaluation(diagnostico_id: str, eval_data: dict) -> str:
    """Persist A10 evaluation to blackboard/onepager/ and return relative path."""
    _ONEPAGER_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{diagnostico_id}_onepager_eval.json"
    path = _ONEPAGER_DIR / filename
    eval_data["timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(eval_data, fh, ensure_ascii=False, indent=2)
    logger.info("One-Pager evaluation saved: %s", path)
    return f"blackboard/onepager/{filename}"


def _get_last_feedback(diagnostico_id: str) -> str:
    """Retrieve the last failure feedback from the evaluation file."""
    filename = f"{diagnostico_id}_onepager_eval.json"
    path = _ONEPAGER_DIR / filename
    if not path.exists():
        return "(no previous evaluation found)"
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        return data.get("feedback", "(no feedback in evaluation)")
    except Exception:
        return "(could not read evaluation file)"


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

async def run_onepager_evaluation(
    diagnostico_id: str,
    onepager_output: dict[str, Any],
    runner: SessionRunner,
) -> tuple[bool, str]:
    """
    Run A10 evaluation on the One-Pager generated by A8.

    Returns:
        (passed: bool, feedback: str)
            passed=True  → One-Pager is approved for client delivery.
            passed=False → A8 should regenerate with the provided feedback.

    Raises:
        OnePagerEscalationError: One-Pager has already been rejected twice.
        LLMError:                Unrecoverable API failure (raised by SessionRunner).
        AgentOutputError:        A10 returned unparseable output (raised by SessionRunner).
    """
    # ── Check retry count ─────────────────────────────────────────────────────
    try:
        state = state_manager.load_state(diagnostico_id)
        retry_count = state["onepager"].get("retry_count", 0)
        if retry_count >= 2:
            raise OnePagerEscalationError(diagnostico_id, _get_last_feedback(diagnostico_id))
    except (FileNotFoundError, KeyError):
        retry_count = 0

    logger.info(
        "═══ ONE-PAGER EVAL (A10) | run=%s | retry=%d ═══",
        diagnostico_id, retry_count,
    )

    # ── Build eval context for A10 ────────────────────────────────────────────
    # The A10 system prompt lives on the Agent object in the Managed Agent
    # environment — SessionRunner delivers context as the user message only.
    acceptance_criteria = _load_acceptance_criteria()

    eval_context = {
        "diagnostico_id": diagnostico_id,
        "one_pager": onepager_output,
        "criterios_aceptacion": acceptance_criteria,
        "instruccion": (
            "Evalúa el One-Pager contra el checklist de 8 criterios de aceptación. "
            "Responde ÚNICAMENTE con JSON válido."
        ),
    }

    # ── Invoke A10 via SessionRunner ──────────────────────────────────────────
    verdict = await asyncio.to_thread(
        runner.run_agent_session, "A10", eval_context, diagnostico_id
    )

    # ── Extract verdict fields ────────────────────────────────────────────────
    passed = bool(verdict.get("aprobado", False))
    feedback = verdict.get("feedback", "") if not passed else ""
    failed_criteria = verdict.get("criterios_fallidos", [])

    # ── Persist evaluation ────────────────────────────────────────────────────
    eval_path = _save_onepager_evaluation(diagnostico_id, verdict)

    # ── Update state ──────────────────────────────────────────────────────────
    try:
        state_manager.update_onepager(
            diagnostico_id,
            {
                "eval_path": eval_path,
                "eval_passed": passed,
                "status": "approved" if passed else "generated",
                "retry_count": retry_count + (0 if passed else 1),
            },
        )
        if passed:
            state_manager.update_pipeline_status(diagnostico_id, "delivered")
        action = "eval_pass" if passed else "eval_fail"
        detail = f"passed={passed}"
        if not passed:
            detail += f" failed_criteria={failed_criteria}"
        state_manager.append_history(diagnostico_id, "A10", action, detail)
    except Exception as exc:
        logger.warning("Could not update state after One-Pager evaluation: %s", exc)

    if passed:
        logger.info("[A10] One-Pager APPROVED | run=%s", diagnostico_id)
    else:
        logger.warning(
            "[A10] One-Pager REJECTED | run=%s | failed=%s | feedback=%s",
            diagnostico_id, failed_criteria, feedback[:100],
        )

    return passed, feedback
