"""
api/app.py
===========
DiagnostiCore FastAPI application with REST endpoints and SSE streaming.

Endpoints:
  POST /api/runs
    Create a new diagnostic run. Returns run_id + JWT Bearer token.

  GET  /api/runs/{run_id}
    Current run status: estado, agents, IDD (if available).
    Requires Bearer token when DIAGNOSTICORE_JWT_SECRET is set.

  POST /api/runs/{run_id}/pipeline
    Trigger the full diagnostic pipeline as a background asyncio task.
    Returns 202 immediately; progress is streamed via GET /stream.
    Requires Bearer token.

  GET  /api/runs/{run_id}/stream
    Server-Sent Events stream. Each event has:
      event: <type>     (agent_start | agent_done | pipeline_done | …)
      data:  <JSON>
    Closes automatically when the pipeline finishes.
    Requires Bearer token.

  GET  /api/runs/{run_id}/report
    Returns the final markdown summary and IDD once the pipeline completes.
    Requires Bearer token.

Authentication:
  Pass: Authorization: Bearer <token>
  Token is generated by POST /api/runs and printed by main.py on new run creation.
  When DIAGNOSTICORE_JWT_SECRET is NOT set, auth is advisory only (warns but allows).

Run:
  uvicorn api.app:app --host 0.0.0.0 --port 8000
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Annotated, Any

from fastapi import Depends, FastAPI, Header, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from sse_starlette.sse import EventSourceResponse

from api.models import (
    AgentStatus,
    ErrorResponse,
    PipelineStartRequest,
    PipelineStartResponse,
    ReportResponse,
    RunCreateRequest,
    RunCreateResponse,
    RunStatusResponse,
)
from api.sse import event_bus
from auth.jwt_auth import TokenError, create_run_token, verify_run_token
from blackboard.blackboard import Blackboard, BlackboardError
from orchestrator import AsyncLLMClient, OrchestratorError, run_full_pipeline
from telemetry.tracing import setup_telemetry

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Pipeline task registry
# Tracks running asyncio.Task per run_id to prevent duplicate pipeline starts.
# ─────────────────────────────────────────────────────────────────────────────

_pipeline_tasks: dict[str, asyncio.Task] = {}


# ─────────────────────────────────────────────────────────────────────────────
# Application lifecycle
# ─────────────────────────────────────────────────────────────────────────────

@asynccontextmanager
async def _lifespan(application: FastAPI):
    """Startup: initialise telemetry. Shutdown: cancel running pipelines."""
    setup_telemetry()
    logger.info("DiagnostiCore API started")
    yield
    # Cancel any still-running pipeline tasks on shutdown
    for run_id, task in list(_pipeline_tasks.items()):
        if not task.done():
            logger.warning("Cancelling pipeline task for run %s on shutdown", run_id)
            task.cancel()
    logger.info("DiagnostiCore API stopped")


# ─────────────────────────────────────────────────────────────────────────────
# FastAPI application
# ─────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="DiagnostiCore API",
    version="1.0.0",
    description="Agentic 360-degree digital maturity diagnostic for SMEs.",
    lifespan=_lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # Tighten in production to your frontend domain
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─────────────────────────────────────────────────────────────────────────────
# Auth dependency
# ─────────────────────────────────────────────────────────────────────────────

def _extract_bearer(authorization: str | None) -> str | None:
    """Parse 'Bearer <token>' header value."""
    if authorization and authorization.startswith("Bearer "):
        return authorization[7:].strip()
    return None


async def _verify_run_access(
    run_id: str,
    authorization: Annotated[str | None, Header()] = None,
) -> str:
    """
    FastAPI dependency that enforces run-scoped token access.

    - If DIAGNOSTICORE_JWT_SECRET is set: token required and verified.
    - If secret is not set: token optional; logs a warning if missing.
    """
    token = _extract_bearer(authorization)
    secret_configured = bool(os.environ.get("DIAGNOSTICORE_JWT_SECRET", "").strip())

    if not token:
        if secret_configured:
            raise HTTPException(
                status_code=401,
                detail="Authorization: Bearer <token> header is required.",
            )
        logger.warning(
            "Unauthenticated access to run %s — set DIAGNOSTICORE_JWT_SECRET to enforce tokens",
            run_id,
        )
        return run_id

    try:
        verify_run_token(token, expected_run_id=run_id)
    except TokenError as exc:
        raise HTTPException(status_code=401, detail=str(exc))

    return run_id


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _get_runs_dir() -> str:
    return os.environ.get("DIAGNOSTICORE_RUNS_DIR", "runs")


def _load_blackboard(run_id: str) -> Blackboard:
    """Load blackboard or raise 404."""
    try:
        return Blackboard(f"{_get_runs_dir()}/{run_id}.json")
    except BlackboardError:
        raise HTTPException(status_code=404, detail=f"Run '{run_id}' not found.")


def _build_agents_status(bb: Blackboard) -> list[AgentStatus]:
    """Build per-agent status list from blackboard data."""
    AGENT_MAP = [
        ("A1", "A1_estrategia"),
        ("A2", "A2_liderazgo"),
        ("A3", "A3_cultura"),
        ("A4", "A4_procesos"),
        ("A5", "A5_datos"),
        ("A6", "A6_tecnologia"),
        ("A7", None),
        ("A8", None),
    ]
    completed = bb.agentes_completados()
    statuses: list[AgentStatus] = []
    for agent_id, dim_key in AGENT_MAP:
        nivel = None
        ts = None
        if dim_key:
            dim_data = bb.get_resultado_dimensional(dim_key) if agent_id in completed else None
            if dim_data:
                nivel = dim_data.get("nivel_madurez")
        if agent_id in completed:
            ts_key = f"{agent_id}_completado"
            ts = bb._data.get("timestamps", {}).get(ts_key)
        statuses.append(AgentStatus(
            agent_id=agent_id,
            completed=agent_id in completed,
            nivel_madurez=nivel,
            timestamp=ts,
        ))
    return statuses


# ─────────────────────────────────────────────────────────────────────────────
# Pipeline background task
# ─────────────────────────────────────────────────────────────────────────────

async def _run_pipeline_task(
    run_id: str,
    model: str,
    api_key: str,
    runs_dir: str,
) -> None:
    """
    Coroutine executed as a background asyncio.Task.
    Runs the full pipeline and emits SSE events on completion/failure.
    The event_bus handles agent-level events internally via agent_runner.
    """
    logger.info("Background pipeline starting | run=%s | model=%s", run_id, model)
    try:
        llm_client = AsyncLLMClient(api_key=api_key, model=model)
        await run_full_pipeline(run_id=run_id, llm_client=llm_client, runs_dir=runs_dir)
        # pipeline_done event is emitted from run_full_pipeline via agent_runner
        logger.info("Background pipeline complete | run=%s", run_id)
    except OrchestratorError as exc:
        logger.error("Background pipeline error | run=%s | %s", run_id, exc)
        # Ensure SSE stream is closed even if the event was not emitted by runner
        event_bus.emit(run_id, "pipeline_error", {
            "run_id": run_id,
            "failed_agents": exc.failed_agents,
            "error": str(exc),
        })
    except Exception as exc:
        logger.exception("Unexpected pipeline error | run=%s", run_id)
        event_bus.emit(run_id, "pipeline_error", {
            "run_id": run_id,
            "failed_agents": [],
            "error": str(exc),
        })
    finally:
        _pipeline_tasks.pop(run_id, None)


# ─────────────────────────────────────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────────────────────────────────────

@app.post(
    "/api/runs",
    response_model=RunCreateResponse,
    status_code=201,
    summary="Create a new diagnostic run",
)
async def create_run(body: RunCreateRequest) -> RunCreateResponse:
    """
    Create a new DiagnostiCore diagnostic run.

    Returns a run_id and a scoped JWT Bearer token.
    Pass the token in the Authorization header for all subsequent calls to this run.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        raise HTTPException(
            status_code=503,
            detail="ANTHROPIC_API_KEY environment variable is not set on the server.",
        )

    bb = Blackboard.crear_run(
        nombre_cliente=body.cliente,
        sector=body.sector,
        consultor=body.consultor,
        tamaño=body.tamanio,
        empleados=body.empleados,
        runs_dir=_get_runs_dir(),
    )
    run_id: str = bb._data["run_id"]

    token = create_run_token(
        run_id=run_id,
        consultor_id=body.consultor,
        ttl_hours=body.token_ttl_hours,
    )
    claims = verify_run_token(token)  # decode to get expires_at

    return RunCreateResponse(
        run_id=run_id,
        token=token,
        created_at=datetime.now(tz=timezone.utc).isoformat(),
        token_expires_at=claims.expires_at.isoformat(),
    )


@app.get(
    "/api/runs/{run_id}",
    response_model=RunStatusResponse,
    summary="Get run status",
)
async def get_run_status(run_id: str = Depends(_verify_run_access)) -> RunStatusResponse:
    """Current state of a diagnostic run including per-agent completion status."""
    bb = _load_blackboard(run_id)
    sintesis = bb.get_sintesis()
    idd = sintesis.get("idd") if sintesis else None
    errores: list[dict[str, Any]] = bb._data.get("metadatos", {}).get("errores", [])

    return RunStatusResponse(
        run_id=run_id,
        estado=bb.get_estado(),
        cliente=bb.get_cliente(),
        agentes_completados=bb.agentes_completados(),
        agents=_build_agents_status(bb),
        errores=errores,
        idd=idd,
    )


@app.post(
    "/api/runs/{run_id}/pipeline",
    response_model=PipelineStartResponse,
    status_code=202,
    summary="Start the diagnostic pipeline",
)
async def start_pipeline(
    body: PipelineStartRequest,
    run_id: str = Depends(_verify_run_access),
) -> PipelineStartResponse:
    """
    Trigger the full A1→A8 pipeline as a background task.

    Returns 202 immediately. Connect to GET /api/runs/{run_id}/stream to
    receive real-time progress via SSE.

    Returns 409 if a pipeline is already running for this run.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        raise HTTPException(
            status_code=503,
            detail="ANTHROPIC_API_KEY is not set on the server.",
        )

    # Verify run exists
    _load_blackboard(run_id)

    # Prevent double-start
    existing_task = _pipeline_tasks.get(run_id)
    if existing_task and not existing_task.done():
        raise HTTPException(
            status_code=409,
            detail=f"Pipeline for run '{run_id}' is already running.",
        )

    task = asyncio.create_task(
        _run_pipeline_task(
            run_id=run_id,
            model=body.model,
            api_key=api_key,
            runs_dir=_get_runs_dir(),
        ),
        name=f"pipeline-{run_id}",
    )
    _pipeline_tasks[run_id] = task

    logger.info("Pipeline task created | run=%s | model=%s", run_id, body.model)
    return PipelineStartResponse(
        run_id=run_id,
        status="started",
        message=(
            f"Pipeline started for run '{run_id}'. "
            f"Connect to GET /api/runs/{run_id}/stream for real-time progress."
        ),
    )


@app.get(
    "/api/runs/{run_id}/stream",
    summary="SSE real-time pipeline progress",
    response_description="text/event-stream",
)
async def stream_pipeline_events(
    request: Request,
    run_id: str = Depends(_verify_run_access),
) -> EventSourceResponse:
    """
    Subscribe to Server-Sent Events for a running pipeline.

    Each event has the form:
      event: <type>
      data: <JSON object>

    The stream closes automatically when the pipeline completes or errors.
    """
    async def _event_generator():
        async for evt in event_bus.subscribe(run_id):
            # SSE keep-alive: check client disconnect on every event
            if await request.is_disconnected():
                logger.debug("SSE client disconnected | run=%s", run_id)
                return
            yield {
                "event": evt["type"],
                "data": json.dumps(evt["data"], ensure_ascii=False),
                "id": evt["timestamp"],
            }

    return EventSourceResponse(_event_generator())


@app.get(
    "/api/runs/{run_id}/report",
    response_model=ReportResponse,
    summary="Get final diagnostic report",
)
async def get_report(run_id: str = Depends(_verify_run_access)) -> ReportResponse:
    """
    Retrieve the final diagnostic report once the pipeline has completed.

    Returns 202 if the pipeline is still running, 404 if the run doesn't exist.
    """
    bb = _load_blackboard(run_id)

    if bb.get_estado() not in ("completado",):
        raise HTTPException(
            status_code=202,
            detail=(
                f"Run '{run_id}' is not yet complete (estado: {bb.get_estado()}). "
                f"Poll GET /api/runs/{run_id} or subscribe to the SSE stream."
            ),
        )

    sintesis = bb.get_sintesis() or {}
    idd: float | None = sintesis.get("idd")
    idd_clasificacion: str | None = sintesis.get("clasificacion")
    causas_raiz = sintesis.get("causas_raiz", [])
    one_pager = bb.get_one_pager()

    return ReportResponse(
        run_id=run_id,
        markdown_summary=bb.to_markdown_resumen(),
        idd=idd,
        idd_clasificacion=idd_clasificacion,
        causas_raiz_count=len(causas_raiz),
        one_pager_available=one_pager is not None,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Health check
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health", include_in_schema=False)
async def health() -> dict:
    return {
        "status": "ok",
        "active_pipelines": list(_pipeline_tasks.keys()),
        "sse_subscribers": {
            run_id: event_bus.subscriber_count(run_id)
            for run_id in event_bus.active_runs()
        },
    }


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    uvicorn.run(
        "api.app:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        log_level="info",
    )
